# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/rust"
    commit-message:
      prefix: "chore"
      include: "scope"
    target-branch: "main"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/rust+wasm"
    commit-message:
      prefix: "chore"
      include: "scope"
    target-branch: "main"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/examples/gen-axum"
    commit-message:
      prefix: "chore(examples)"
      include: "scope"
    target-branch: "main"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    target-branch: "main"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/rust"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    target-branch: "main"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/rust+wasm"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    target-branch: "main"
    schedule:
      interval: "weekly"
