name: 🐳 Docker

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ '*' ]

concurrency:
  group: {{ "${{ github.workflow " }}}}-{{ "${{ github.ref " }}}}
  cancel-in-progress: true

jobs:
  build-docker:
    runs-on: ubuntu-latest
    if: {{ "${{ github.event_name == 'pull_request' " }}}}

    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # https://github.com/docker/setup-qemu-action
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      # https://github.com/docker/setup-buildx-action
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: "--debug"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: {{ "${{ github.repository_owner " }}}}
          password: {{ "${{ secrets.GITHUB_TOKEN " }}}}

      - name: Docker Build
        uses: docker/build-push-action@v3
        with:{% if dockerbuild == "glibc" %}
          build-args: |
            RUST_BUILD_IMG=rust:1.65-slim-bullseye
            DEBIAN_TAG=bullseye-slim
          {% else %}
          build-args: |
            RUST_BUILD_IMG=rust:1.65-slim-bullseye{% endif %}
          cache-from: type=registry,ref=ghcr.io/{{ "${{ github.repository_owner " }}}}/{{project-name}}:latest
          cache-to: type=registry,ref=ghcr.io/{{ "${{ github.repository_owner " }}}}/{{project-name}}:latest,mode=max
          context: .{% if dockerbuild == "glibc" %}
          # We don't add `linux/arm64` here, as it can cause GitHub runners to
          # stall for too long.
          platforms: linux/amd64
          {% else %}
          platforms: linux/amd64, linux/arm64{% endif %}
          push: false
          tags: |
            {{ "${{ github.repository_owner " }}}}/{{project-name}}:latest

  push-docker-build:
    runs-on: ubuntu-latest
    if: {{ "${{ github.event_name == 'push' " }}}}

    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # https://github.com/docker/setup-qemu-action
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      # https://github.com/docker/setup-buildx-action
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: "--debug"

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: {{ "${{ secrets.DOCKERHUB_USERNAME " }}}}
          password: {{ "${{ secrets.DOCKERHUB_TOKEN " }}}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: {{ "${{ github.repository_owner " }}}}
          password: {{ "${{ secrets.GITHUB_TOKEN " }}}}

      - name: Docker Build and Push
        uses: docker/build-push-action@v3
        with:{% if dockerbuild == "glibc" %}
          build-args: |
            RUST_BUILD_IMG=rust:1.65-slim-bullseye
            DEBIAN_TAG=bullseye-slim
          {% else %}
          build-args: |
            RUST_BUILD_IMG=rust:1.65-slim-bullseye{% endif %}
          cache-from: type=registry,ref=ghcr.io/{{ "${{ github.repository_owner " }}}}/{{project-name}}:latest
          cache-to: type=registry,ref=ghcr.io/{{ "${{ github.repository_owner " }}}}/{{project-name}}:latest,mode=max
          context: .{% if dockerbuild == "glibc" %}
          # We don't add `linux/arm64` here, as it can cause GitHub runners to
          # stall for too long.
          platforms: linux/amd64
          {% else %}
          platforms: linux/amd64, linux/arm64{% endif %}
          push: true
          tags: |
            {{ "${{ github.repository_owner " }}}}/{{project-name}}:latest
            ghcr.io/{{ "${{ github.repository_owner " }}}}/{{project-name}}:latest
