[template]
ignore = [
    ".git",
    "pre-script.rhai"
]

[hooks]
pre = ["pre-script.rhai"]

[placeholders.github-name]
type = "string"
prompt = "Enter your GitHub username or org?"
regex = "^[A-Za-z0-9][A-Za-z0-9-]{0,38}$"

[placeholders.github-codeowner]
type = "string"
prompt = "Who is the GitHub codeowner - GitHub user or org/team?"

[placeholders.description]
type = "string"
prompt = "Enter a description of the project."
default = ""

[placeholders.github-actions]
type = "bool"
prompt = "Set up GitHub Actions CI/CD workflows?"
default = true

[placeholders.dependabot]
type = "bool"
prompt = "Enable Dependabot prs/checks?"
default = true

[conditional.'github-actions == true'.placeholders.codecov]
type = "bool"
prompt = "Enable codecov coverage upload via GitHub Actions?"
default = true

[placeholders.toolchain]
type = "string"
prompt = "Which rust toolchain version do you want?"
choices = ["stable", "beta", "nightly"]
default = "stable"

[placeholders.nix]
type = "bool"
prompt = "Set up a Nix flake?"
default = true

[placeholders.node-or-web]
type = "string"
prompt = "What is your rust-generated wasm package targeting?"
choices = ["bundler", "nodejs", "web"]
default = "web"

[placeholders.have-discord]
type = "bool"
prompt = "Link a discord community?"
default = true

[conditional.'have-discord == true'.placeholders.discord-link]
type = "string"
prompt = "Enter a discord invite link?"

[placeholders.license]
type = "string"
prompt = "What license to use?"
choices = ["Apache", "MIT", "dual"]
default = "Apache"

[conditional.'crate_type == "lib"']
ignore = [
    "{{project-name}}/src/main.rs",
    "{{project-name}}/Cargo.lock",
]

[conditional.'crate_type == "bin"']
ignore = [
    "{{project-name}}/src/lib.rs",
    "{{project-name}}/examples"
]

[conditional.'nix == false']
ignore = [
    ".envrc",
    "flake.nix",
]

[conditional.'github-actions == false']
ignore = [
   ".github/workflows",
]

[conditional.'dependabot == false']
ignore = [
   ".github/dependabot.yml",
]

[conditional.'codecov == false']
ignore = [
   ".github/workflows/coverage.yml",
   "codecov.yml"
]
