ignore:
  - "{{project-name}}/tests"
  - "{{project-name}}-wasm"{% if bench %}
  - "{{project-name}}-benches"{% endif %}
  - "examples"

comment:
  layout: "reach, diff, flags, files"
  require_changes: true

github_checks:
  annotations: false

coverage:
  status:
    project:
      default:
        threshold: 5%
