ignore:
  - "tests"

comment:
  layout: "reach, diff, flags, files"
  require_changes: true

github_checks:
  annotations: false

coverage:
  status:
    project:
      default:
        threshold: 5%
