[monitoring]
process_collector_interval = 10

[otel]
exporter_otlp_endpoint = "http://localhost:4317"

[server]
environment = "local"
metrics_port = {{metricsport}}
port = {{port}}
timeout_ms = 30000
