name: 🏪 Build Template

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ '*' ]

jobs:
  generate-templates:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: fission-codes-rust-template
    strategy:
      fail-fast: false
      matrix:
        templates:
          - rust
          - rust+wasm
        crate_type:
          - lib
          - bin
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup cargo-generate
        uses: cargo-generate/cargo-generate-action@v0.16.0
        with:
          name: ${{ env.PROJECT_NAME }}
          subfolder: ${{ matrix.templates }}
          template_values_file: .github/workflows/template_values.toml
          other: "--${{ matrix.crate_type }}"

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: stable

      - name: Install Rust-Nighly Toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          components: rustfmt
          toolchain: nightly

      - name: Install Cargo Audit
        uses: actions-rs/cargo@v1
        with:
          args: --force cargo-deny
          command: install

      # move generated project to temp folder:
      # https://github.com/rust-lang/cargo/issues/9922
      - name: Check If Repository Formats, Lints, Checks
        run: |
          mv $PROJECT_NAME ${{ runner.temp }}/
          cd ${{ runner.temp }}/$PROJECT_NAME
          cargo clippy
          cargo +nightly fmt --all -- --check
          cargo deny check

  nix-flake-check:
    runs-on: ubuntu-latest
    env:
      ## force it last for cargo-sort
      PROJECT_NAME: fission-codes-rust-template
    strategy:
      fail-fast: false
      matrix:
        templates:
          - rust
          - rust+wasm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup cargo-generate
        uses: cargo-generate/cargo-generate-action@v0.16.0
        with:
          name: ${{ env.PROJECT_NAME }}
          subfolder: ${{ matrix.templates }}
          template_values_file: .github/workflows/template_values.toml
          other: "--lib"

      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Nix Flake/Develop Checks - Rust Template
        if: ${{ matrix.templates == 'rust' }}
        run: |
          mv $PROJECT_NAME ${{ runner.temp }}/
          cd ${{ runner.temp }}/$PROJECT_NAME
          git init
          git add .
          nix flake check
          nix develop --show-trace -c rustc --version
          nix develop --show-trace -c cargo udeps --version
          nix develop --show-trace -c irust --version
          nix develop --show-trace -c pre-commit --version

      - name: Nix Flake/Develop Checks - Rust+Wasm Template
        if: ${{ matrix.templates == 'rust+wasm' }}
        run: |
          mv $PROJECT_NAME ${{ runner.temp }}/
          cd ${{ runner.temp }}/$PROJECT_NAME
          git init
          git add .
          nix flake check
          nix develop --show-trace -c rustc --version
          nix develop --show-trace -c wasm-pack --version

  run-pre-commit:
    runs-on: ubuntu-latest
    env:
      ## force it last for cargo-sort
      PROJECT_NAME: zfission-codes-rust-template
    strategy:
      fail-fast: false
      matrix:
        templates:
          - rust
          - rust+wasm
        crate_type:
          - lib
          - bin
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup cargo-generate
        uses: cargo-generate/cargo-generate-action@v0.16.0
        with:
          name: ${{ env.PROJECT_NAME }}
          subfolder: ${{ matrix.templates }}
          template_values_file: .github/workflows/template_values.toml
          other: "--${{ matrix.crate_type }}"

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: stable

      - name: Install Rust-Nighly Toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          components: rustfmt
          toolchain: nightly

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Install pre-commit Hooks
        run: pre-commit install

      - name: Run Cargo-check & Then pre-commit on All Files
        run: |
          mv $PROJECT_NAME ${{ runner.temp }}/
          cd ${{ runner.temp }}/$PROJECT_NAME
          git init
          git add .
          cargo check
          pre-commit run --all-files --show-diff-on-failure

  test-rust-project:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: fission-codes-rust-template
    strategy:
      fail-fast: false
      matrix:
        crate_type:
          - lib
          - bin
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup cargo-generate
        uses: cargo-generate/cargo-generate-action@v0.16.0
        with:
          name: ${{ env.PROJECT_NAME }}
          subfolder: rust
          template_values_file: .github/workflows/template_values.toml
          other: "--${{ matrix.crate_type }}"

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable

      - name: Run Tests
        run: |
          mv $PROJECT_NAME ${{ runner.temp }}/
          cd ${{ runner.temp }}/$PROJECT_NAME
          cargo test --all-features

  test-rust-wasm-project:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: fission-codes-rust-template
    strategy:
      fail-fast: false
      matrix:
        crate_type:
          - lib
          - bin
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup cargo-generate
        uses: cargo-generate/cargo-generate-action@v0.16.0
        with:
          name: ${{ env.PROJECT_NAME }}
          subfolder: rust+wasm
          template_values_file: .github/workflows/template_values.toml
          other: "--${{ matrix.crate_type }}"

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Run Tests
        run: |
          mv $PROJECT_NAME ${{ runner.temp }}/
          cd ${{ runner.temp }}/$PROJECT_NAME/$PROJECT_NAME
          cargo test --all-features
          cd ../$PROJECT_NAME-wasm
          wasm-pack test --headless --firefox --chrome

  test-benchmark:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: fission-codes-rust-template
    strategy:
      fail-fast: false
      matrix:
        templates:
          - rust
          - rust+wasm
        crate_type:
          - lib
          - bin
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup cargo-generate
        uses: cargo-generate/cargo-generate-action@v0.16.0
        with:
          name: ${{ env.PROJECT_NAME }}
          subfolder: ${{ matrix.templates }}
          template_values_file: .github/workflows/template_values.toml
          other: "--${{ matrix.crate_type }}"

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable

      - name: Run Benchmark - Rust Template
        if: ${{ matrix.templates == 'rust' }}
        run: |
          mv $PROJECT_NAME ${{ runner.temp }}/
          cd ${{ runner.temp }}/$PROJECT_NAME
          cargo bench --all-features -- --output-format bencher | tee output.txt

      - name: Run Benchmark - Rust+Wasm Template
        if: ${{ matrix.templates == 'rust+wasm' }}
        run: |
          mv $PROJECT_NAME ${{ runner.temp }}/
          cd ${{ runner.temp }}/$PROJECT_NAME
          cargo bench -p $PROJECT_NAME-benches -- --output-format bencher | tee output.txt

  test-docker:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: fission-codes-rust-template
    strategy:
      fail-fast: false
      matrix:
        templates:
          - rust
          - rust+wasm
        dockerbuild:
          - glibc
          - musl

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup cargo-generate
        uses: cargo-generate/cargo-generate-action@v0.16.0
        with:
          name: ${{ env.PROJECT_NAME }}
          subfolder: ${{ matrix.templates }}
          template_values_file: .github/workflows/template_values.toml
          other: "--bin -d docker=true -d dockerbuild=${{ matrix.dockerbuild }}"

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: "--debug"

      - name: Docker Build MUSL - Rust Template
        if: ${{ matrix.dockerbuild == 'musl' && matrix.templates == 'rust' }}
        run: |
          mv $PROJECT_NAME ${{ runner.temp }}/
          cd ${{ runner.temp }}/$PROJECT_NAME
          docker buildx build \
          --cache-from type=gha --cache-to type=gha,mode=max \
          --platform=linux/amd64,linux/arm64 \
          --tag $PROJECT_NAME:latest \
          --progress tty .

      - name: Docker Build MUSL - Rust+Wasm Template
        if: ${{ matrix.dockerbuild == 'musl' && matrix.templates == 'rust+wasm' }}
        run: |
          mv $PROJECT_NAME ${{ runner.temp }}/
          cd ${{ runner.temp }}/$PROJECT_NAME
          docker buildx build \
          --cache-from type=gha --cache-to type=gha,mode=max \
          --platform=linux/amd64,linux/arm64 \
          --tag $PROJECT_NAME:latest \
          --file docker/Dockerfile \
          --progress tty .

      - name: Docker Build GLIBC - Rust Template
        if: ${{ matrix.dockerbuild == 'glibc' && matrix.templates == 'rust' }}
        run: |
          mv $PROJECT_NAME ${{ runner.temp }}/
          cd ${{ runner.temp }}/$PROJECT_NAME
          docker buildx build \
          --cache-from type=gha --cache-to type=gha,mode=max \
          --platform=linux/amd64 \
          --tag $PROJECT_NAME:latest \
          --progress tty .

      - name: Docker Build GLIBC - Rust+Wasm Template
        if: ${{ matrix.dockerbuild == 'glibc' && matrix.templates == 'rust+wasm' }}
        run: |
          mv $PROJECT_NAME ${{ runner.temp }}/
          cd ${{ runner.temp }}/$PROJECT_NAME
          docker buildx build \
          --cache-from type=gha --cache-to type=gha,mode=max \
          --platform=linux/amd64 \
          --tag $PROJECT_NAME:latest \
          --file docker/Dockerfile \
          --progress tty .
