[values]
codecov = true
description = "Rust template for project."
dependabot = true
discord = ""
github_actions = true
github-codeowner = "rush/geddylee"
github-name = "geddylee"
have_discord = true
discordlink = "http://discord.link"
license = "dual"
nix = true
node-or-web = "web"
toolchain = "stable"
