[values]
auditable = true
bench = true
codecov = true
description = "Rust template for project."
dependabot = true
github_actions = true
github-codeowner = "rush/geddylee"
github-email = "flybynight@subdivisions.com"
github-name = "geddylee"
have_discord = true
discordlink = "http://discord.link"
docker = false
license = "dual"
nix = true
node-or-web = "web"
repo-name = "fission-codes"
toolchain = "stable"
